version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://root:root@db:5432/lms_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
volumes:
  postgres_data:
